# Generated by Django 6.0 on 2025-12-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.CharField(blank=True, choices=[('econ', '경제학'), ('cs', '컴퓨터과학'), ('math', '수학'), ('stat', '통계학'), ('physics', '물리학')], max_length=10),
        ),
    ]
