# Generated by Django 6.0 on 2025-12-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='summary',
        ),
        migrations.AddField(
            model_name='paper',
            name='detail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
